/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 8.1
 */
import javax.swing.table.*;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
public class _1_LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form _1__LOGIN
     */
    public _1_LOGIN() {
        initComponents();
    }
Statement stmt=null;
ResultSet rs=null;
String SQL;
public static String Id;
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        InvalidLBL = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        regLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 230, 194, 71);

        user.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        user.setToolTipText("Enter user id here");
        getContentPane().add(user);
        user.setBounds(340, 140, 320, 60);

        pass.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pass.setToolTipText("enter your password");
        pass.setEchoChar('*');
        getContentPane().add(pass);
        pass.setBounds(340, 230, 320, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 30, 120, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("UserName");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 150, 194, 50);

        InvalidLBL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        InvalidLBL.setForeground(new java.awt.Color(255, 0, 0));
        InvalidLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(InvalidLBL);
        InvalidLBL.setBounds(120, 300, 540, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("LOG  IN");
        jButton2.setToolTipText("");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 360, 170, 50);

        regLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regLbl.setForeground(new java.awt.Color(255, 255, 255));
        regLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regLbl.setText("Don't have a Login ?, Click here to Register !");
        regLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regLblMouseClicked(evt);
            }
        });
        getContentPane().add(regLbl);
        regLbl.setBounds(210, 410, 340, 51);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 360, 160, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/6.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, -10, 790, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try   {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Mystogan", "root", "root");
            String sql = "select * from login where username = ? and password = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1 ,user.getText());
            pst.setString(2 ,pass.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                _3_MENU m= new _3_MENU();
                m.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                InvalidLBL.setText("Incorrect Username or Password");
            }
        } catch (Exception e)
        {
            InvalidLBL.setText("Incorrect Username or Password");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed

    }//GEN-LAST:event_jButton2KeyPressed

    private void regLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regLblMouseClicked
        _2_REGISTER r = new _2_REGISTER();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regLblMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       user.setText("");
       pass.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_1_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_1_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_1_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_1_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _1_LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InvalidLBL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel regLbl;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

    private static class con {

        private static PreparedStatement prepareStatement(String sql) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public con() {
        }
    }
}
